### ISSUE TITLE
[ Request ] Contribute this to Community Prompts package

### ISSUE THREAD

**Issue by ProjektGopher** [macocci7/file-selector-prompt#5]
I'd love to include this feature in our [Community Prompts](https://github.com/artisan-build/community-prompts) package!

If you can take your original PR to Laravel and change the target I can help get it to be compatible. I've got some **really** cool new prompt features being developed, and I think this would fit in nicely.

**Comment by macocci7** [comment]
> I'd love to include this feature in our [Community Prompts](https://github.com/artisan-build/community-prompts) package!
> 
> If you can take your original PR to Laravel and change the target I can help get it to be compatible. I've got some **really** cool new prompt features being developed, and I think this would fit in nicely.

@ProjektGopher Sounds nice!

I'd love to do that.
But I don't know the details of how to do that.
Should I re-open the original PR changing the `base repository` somewhere else?

**Comment by ProjektGopher** [comment]
Even though I forked off of laravel/prompts, I detatched my fork because it had diverged so much from the original. It might make the most sense to fork our new repo, and just work on copying things over, otherwise you'll spend a year squashing conflicts, haha

**Comment by macocci7** [comment]
OK! I'll do that.

**Comment by macocci7** [comment]
@ProjektGopher I opened PR [#5](https://github.com/artisan-build/community-prompts/pull/5) on Community Prompts.
Please check it out.

**Comment by ProjektGopher** [comment]
Moving discussion to https://github.com/artisan-build/community-prompts/pull/5
